# mainly from MDTraj appveyor
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\develop\\appveyor-ci\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1
  BINSTAR_TOKEN:
    secure: LJUoqxkUbcJR0UnL2Ap7/dLquM6cX8i1JC0mXNvwXEbTTVW3C98qQ/JlJWzAYpoy


  matrix:
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "27"
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "27"
      ARCH: "64"
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "34"
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      ARCH: "64"
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      ARCH: "64"
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "36"
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      ARCH: "64"


install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - conda update -yq --all
  - conda install -yq conda-build jinja2
  - conda install python=%CONDA_PY:~0,1%.%CONDA_PY:~1,2% -y
#  - python -E -V
  - conda build --quiet develop\\conda-recipe
  - conda install --use-local mdsrv -y


build: false


test_script:  
  - "%CMD_IN_ENV% mdsrv -h"


deploy_script:
  - echo "Starting Deployment"
  # upload conda builds to conda cloud
  - cmd: set PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%
  # because appveyor prints to stderror, we will run it in command mode by doing a check first
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { $env:conda_upload = 'true' } Else { write-output "Not on a tag on master, won't deploy to anaconda" }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %BINSTAR_TOKEN% upload .\win-*\*.tar.bz2 -u j0kaso --no-progress --force


notifications:
  email: false